import Head from "next/head";
import NextLink from "next/link";
import React, { ReactNode } from "react";

type LayoutProps = {
  children: ReactNode;
};

type NavItem = {
  label: string;
  pathname: string;
};

const navItems: NavItem[] = [
  { label: "Questions", pathname: "/" },
  { label: "Input", pathname: "/input-react-key" },
  { label: "React Strict Mode", pathname: "/react-strict" },
  { label: "React Life Cycle", pathname: "/react-life-cycle" },
  { label: "JSON Comparison", pathname: "/json-comparison" },
  { label: "CSS Center", pathname: "/center" },
  { label: "Counter", pathname: "/counter" },
  { label: "Memoize", pathname: "/memoize" },
];

function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "20px" }}>
        <div style={{ display: "flex", gap: "10px", marginBottom: "20px" }}>
          {navItems.map((item) => (
            <NextLink key={item.label} href={item.pathname}>
              {item.label}
            </NextLink>
          ))}
        </div>
        <div>{children}</div>
      </div>
    </>
  );
}

export default Layout;
